DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `products`;

CREATE TABLE `users` (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) UNIQUE NOT NULL,
	password VARCHAR(254) NOT NULL
);

CREATE TABLE `products` (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    product_code VARCHAR(20) UNIQUE NOT NULL
);
